name: Run Tests
on: [push, pull_request]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install actions-poetry
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.10
          poetry_version: 1.0.5
          working_directory: .
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.6.10
          poetry_version: 1.0.5
          working_directory: .
          args: run python -m pytest
